### PR TITLE
Upgrade bootstrap to version 5

### PR DESCRIPTION
**Pull request by yeungon**
Upgrading to the latest Boostrap (5.0) version. jQuery is optional then.

### CODE REVIEW

**Comment by dvbui** [comment]
Some parts, namely the search box and the links, are broken after upgrading to Bootstrap v5.0

**Comment by dvbui** [comment]
Contributions are still welcomed.

**Comment by yeungon** [comment]
@dvbui I might clean up a bit more on this branch.

**Review by dvbui — COMMENTED** [review]
The clientValidation is not needed since it is already handled by the backend. However, an alert showing result["message"] when result["status"] is False is definitely a nice addition.

**Comment by dvbui** [comment]
One concern is that the links on Bootstrap 5 does not look as great as links on Bootstrap 4

Bootstrap 4
Screenshot from 2022-01-20 23-07-48

Bootstrap 5
Screenshot from 2022-01-20 23-07-48

**Comment by yeungon** [comment]
@dvbui Yeah, you might see that all validation will be handled first by the client as it reduces the workload of the server. Then later we have to deal with bots as well. 

No worry about the style. I am quite confident about the style and decorative stuff :-))

**Comment by dvbui** [comment]
I merged because we have a better homepage. Other pages also need to be upgraded as well (many search forms are broken after the upgrade, but they need a re-design anyway).

**Comment by yeungon** [comment]
Sure, let's me hand the client for you :-))

**Pull request merged**
