### PR TITLE
Remove duplicate css file and upgrade to the latest bootstrap 5.1.3

### PR DESCRIPTION
**Pull request by yeungon**
upgrade first, remove duplocated css files

### CODE REVIEW

**Comment by yeungon** [comment]
I am not sure whether Flash supports a kind of "global" style. That would be great if that is the case @dvbui 

I then created a globalstyle.css where we import boostrap.css once and reuse them everywhere.

**Comment by dvbui** [comment]
I have reviewed your pull request, and it seems to be that different pages have different designs (ranging from too simple to too complicated in my opinion). Moreover, the main issue (nicer search form) does not seem to be addressed. As a result, I would not accept this pull request.

Screenshot from 2022-01-23 22-09-15

Screenshot from 2022-01-23 22-10-01

With that said, I would take the idea to have something "global"

**Comment by yeungon** [comment]
Here is how it looks like on my computer. @dvbui 

Screenshot from 2022-01-24 14-44-16


Screenshot from 2022-01-24 14-44-00

**Comment by yeungon** [comment]
another one.

Screenshot from 2022-01-24 14-44-00

**Pull request closed without merging**
